### ISSUE TITLE
[FEA] Bump minimum required CMake version to 3.22.3

### ISSUE THREAD

**Issue by robertmaynard** [rapidsai/rapids-cmake#78] opened 2021-09-10 13:03 UTC
**Is your feature request related to a problem? Please describe.**
We should continue leveraging latest CMake improvements, and therefore should review
the improvements that 3.21 and 3.22 will bring to rapids-cmake.

**Describe the solution you'd like**
I would like to see 3.22 become the required CMake version for rapids-cmake 22.X versions

**Additional context**
CMake 3.21 would bring in the following improvements:

- set behavior in regards to local/cache variables is not consistent!!! This is big quality of life improvement
- WriteBasicConfigVersion supports CalVer strings, so workaround in rapids-export can be dropped
- Less false positive error reports from FindThreads
- nicer ways to specify toolchain and install directory from the command line
- improvements to `install()` to copy runtime dependency will need to be reviews and we can see if they can be used when thirdparty dependencies are missing install rules
- Cleanup of ` foreach()` and variable leaking. Most likely will need to update rapids-cmake in places due to this

CMake 3.22 would bring in the following improvements:
- find_library: Infer library prefix and suffix when in script mode. This is important to rapids-cmake as we hook up to projects before the project call which is analogous to script mode.
- compile_features ignore features for non-enabled languages. This allows projects to express a cxx_std_17 requirement and not fail when used by a project that doesn't enable CUDA.
- CUDA language level isn't inferred by the C++ language level
- GNUInstallDirs now aware of conda lib directory requirements

**Comment by kkraus14** [comment] 2022-02-15 14:52
Potential issue with moving to CMake 3.22:
- Apache Arrow currently pins the AWS SDK to to 1.8.x due to a bug: https://github.com/aws/aws-sdk-cpp/issues/1809
- AWS SDK 1.8.x and earlier 1.9.x versions have a bug with CMake 3.22 that prevents it from being used: https://github.com/aws/aws-sdk-cpp/issues/1820
- libcudf depends on Apache Arrow

**Comment by robertmaynard** [comment] 2022-02-15 15:25
@kkraus14 I believe that the 3.22.0 regression that hit AWS SDK was found during the RC cycle. And the fixe is in 3.22.0 ( https://github.com/aws/aws-sdk-cpp/pull/1810 ).

Are you able to confirm this by building the AWS SDK with 3.22.0?

**Comment by robertmaynard** [comment] 2022-02-15 15:38
Weird I thought that the following fix for 3.22.0 would fix the problem and only 3.22.0-rc1 and rc2 would have the regression.

https://gitlab.kitware.com/cmake/cmake/-/merge_requests/6442

**Comment by kkraus14** [comment] 2022-02-15 16:53
> Weird I thought that the following fix for 3.22.0 would fix the problem and only 3.22.0-rc1 and rc2 would have the regression.
> 
> https://gitlab.kitware.com/cmake/cmake/-/merge_requests/6442

I've only tested CMake 3.22.2 since that's what's in conda-forge but can confirm that it reproduces the bug above.

**Comment by robertmaynard** [comment] 2022-02-15 18:03
> > Weird I thought that the following fix for 3.22.0 would fix the problem and only 3.22.0-rc1 and rc2 would have the regression.
> > https://gitlab.kitware.com/cmake/cmake/-/merge_requests/6442
> 
> I've only tested CMake 3.22.2 since that's what's in conda-forge but can confirm that it reproduces the bug above.

I was able to reproduce and you are correct this was never properly fixed. I have re-opened the CMake issue and we should be able to get a fix for 3.22.2+

**Comment by kkraus14** [comment] 2022-02-15 19:02
Thanks @robertmaynard!

**Comment by vyasr** [comment] 2022-02-17 01:32
rmm-python would also benefit from this bump since when we switch to scikit-build we are currently required to include CUDA as one of the project languages due to the way that the C++ rmm component adds libcudacxx's c++17 features to its interface.

**Comment by robertmaynard** [comment] 2022-03-07 14:28
> Thanks @robertmaynard!

This regression has been fixed in the [3.21.6](https://discourse.cmake.org/t/cmake-3-21-6-available-for-download/5165), and [3.22.3](https://discourse.cmake.org/t/cmake-3-22-3-available-for-download/5166) patch releases and the upcoming 3.23.0.

CMake does consider this to be invalid `while` syntax, and 3.24 will have a policy that makes this a explicit syntax error ( https://gitlab.kitware.com/cmake/cmake/-/merge_requests/7045 )

**Closed** 2022-08-29 16:44 UTC
Labels: feature request, 1 - On Deck, tech debt
